version: 1
title:
  patterns:
    - '[Rr]elease\/v[0-9]+(\.[0-9]+){2,3}'
    - '^(?![Ff]eature\/)^(?![Bb]ug\/)^\[SIM-\d+\]\s.{1,59}$'
  error: 'The title can not be longer than 65 characters and must not be named as the branch name'
body:
  patterns:
    - '\[SIM-\d+\]'
    - '^Merge|^Release'
  error: 'The body must contain the issue key: [SIM-XXX]'
reviewers:
  minimum: 1
labels:
  - bug
  - feature
  - Release