name: Create Tag

on:
  push:
    branches:
      - develop

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ButlerLogic/action-autotag@stable
        with:
          tag_prefix: "v"
          strategy: package
          root: "Assets/Package" 